### PR TITLE
Miscellaneous bug fixes

### LINKED ISSUE #49: Person can be created with a blank slug

### PR DESCRIPTION
**Pull request by snowsignal**
I'm killing two birds with one stone here. This closes #49, and also removes the unnecessary `quantity != null` check in `NewRequest.isValid`.

### CODE REVIEW

File: backend/src/main/kotlin/me/andrewda/models/Person.kt [hunk 1]
```diff
@@ -14,7 +14,7 @@ data class NewPerson(
     @Expose val slug: String?,
     @Expose val funds: Double?
 ) {
-    val isValid get() = name != null && slug != null && !slug.isNullOrBlank()
+    val isValid get() = name.isNullOrBlank() && slug.isNullOrBlank()
```
Comment (andrewda) [inline backend/src/main/kotlin/me/andrewda/models/Person.kt]:
```suggestion
    val isValid get() = !name.isNullOrBlank() && !slug.isNullOrBlank()
```

**Review by andrewda — CHANGES_REQUESTED** [review]

**Review by andrewda — APPROVED** [review]
